### ISSUE TITLE
可以在训练中使用pair数据嘛

### ISSUE THREAD

**Issue by 649459021** [csjliang/LPTN#11]
我将yml文件中的训练数据集改为PairedImageDataset，但会报错没有ref

**Comment by csjliang** [comment]
你好，可以使用paired数据。改为```PairedImageDataset```后，需要对应修改```codes/models/lptn_model.py```，把```self.ref```替换为```self.gt```。另外注意pixel loss应改为```self.output```与```self.gt```的差。

**Comment by 649459021** [comment]
您的意思是在该文件123行改为 `l_g_pix = self.cri_pix(self.output, self.gt)`嘛

**Comment by csjliang** [comment]
是的，pair的数据各像素是一一对应的，可以直接使用MSE或MAE损失进行约束。

**Comment by 649459021** [comment]
明白了，多谢您的解答
