### ISSUE TITLE
semantic segmentation

### ISSUE THREAD

**Issue by seekingdeep** [csjliang/LPTN#12]
@csjliang hi there,
Can LPTN be used for semantic segmentation?

**Comment by csjliang** [comment]
Hi, Thanks for your question.
Semantic segmentation relies on the deep representation of both low- and high-frequency components, especially on the boundary among different subjects. Directly applying the LPTN to the semantic segmentation task (by considering the semantic segmentation as a translation from images to segmentation maps) can hardly work well, as the LPTN is too light-weighted to learn deep semantic features on high-frequency. However, the frequency decomposition spirit is still worthy to be validated on such high-level tasks, to either boost the performance or to improve efficiency.

**Comment by seekingdeep** [comment]
thanks
