### ISSUE TITLE
train PairedImageDataset on fivek 

### ISSUE THREAD

**Issue by semchan** [csjliang/LPTN#14]
I follow [here ](https://github.com/csjliang/LPTN/issues/11) to use your code to train PairedImageDataset on fivek . After 20000 iters, I check the training results and find the phenomenon of "over exposure" (as shown in the figure below, the right is the input, the middle is the prediction result, and the left is GT). All training super parameters are the default configuration in your code. Can you help to guide me on how to reduce the "over exposure"? thanks a lot.

![D1645D64@F008A51E F0C5C260 jpg_recompress](https://user-images.githubusercontent.com/20419555/122011870-25ccf900-cdef-11eb-902e-5800c26b2d45.jpg)

**Comment by csjliang** [comment]
Hi
I have replied your email several days ago (you send me the same figure and the same question). Please try to remove or decrease the weight of the Discriminator loss when you use paired training data. Thanks.

**Comment by semchan** [comment]
> Hi
> I have replied your email several days ago (you send me the same figure and the same question). Please try to remove or decrease the weight of the Discriminator loss when you use paired training data. Thanks.

Thanks for your quick reply. Sorry, I didn't receive the email (maybe system error^_^), so I'm asking here. OK, I will follow your suggestion to try. Thanks again.

**Comment by semchan** [comment]
Hi, according to your guidance, I removed GAN loss and only used pixel loss (MSE constraint), which looks good. Thank you very much.
![a0002-dgw_005_400](https://user-images.githubusercontent.com/20419555/122317525-46f92b00-cf50-11eb-9abd-11f905570277.jpg)
