### ISSUE TITLE
关于训练时图片分辨率的问题

### ISSUE THREAD

**Issue by linhl97** [csjliang/LPTN#16]
您好，非常感谢开源相关代码！
想请教一下在train config里面，训练时图片分辨率默认为256，这样经过3层金字塔，最终在32x32分辨率上去做trans low，在我自己的数据集上训练时感觉尺度太粗糙了难以完成转换，不知道我是否哪个步骤理解有误

**Comment by csjliang** [comment]
你好，感谢关注我们的工作。
默认配置的低频分量确实是32*32，当然，在显存和训练时间允许的条件下，你可以提高训练分辨率，以效率换性能，但我们实验发现在低分辨率上训练的结果同样适用于高分辨率测试（PSNR下降很小），主要是因为：1 金字塔的良好性质，低频分量在合理范围内与尺度无关，总能概括图像的低频信息；2 本文提出的渐进mask策略，高频的处理同样引入了深度信息，也就是图像的每个频段都得到了处理。
