### ISSUE TITLE
图像去反光

### ISSUE THREAD

**Issue by qmlu-cn** [csjliang/LPTN#17]
@csjliang 您好，
问下LPTN可以用于高分辨率图像去反光的任务吗？

**Comment by csjliang** [comment]
你好，感谢关注。
理论上LPTN可以用于所有的修改图像低频（同时进行高频refine）的任务，图像反光区域多涉及低频分量，可以尝试，我没做过类似的实验。

**Comment by qmlu-cn** [comment]
> 你好，感谢关注。
> 理论上LPTN可以用于所有的修改图像低频（同时进行高频refine）的任务，图像反光区域多涉及低频分量，可以尝试，我没做过类似的实验。

感谢回答，我尝试一下看看效果。有问题再跟您讨论。
