### ISSUE TITLE
复现结果颜色发红

### ISSUE THREAD

**Issue by wml666** [csjliang/LPTN#19]
您好，我按照补充材料里面给出的细节训练模型，测试结果图片颜色整体有点泛红，并且psnr随着训练迭代逐渐变小，请问这种情况遇到过吗？
![image](https://user-images.githubusercontent.com/41294720/125898902-cea0f5f2-c4d3-41f3-a167-7cb4b4cdcb80.png)
![image](https://user-images.githubusercontent.com/41294720/125898926-027e387f-138a-40f6-8030-82db3455e17e.png)
![image](https://user-images.githubusercontent.com/41294720/125898941-f6ab8f31-d5a6-464f-8ed8-f8cd4d36e2b7.png)
![image](https://user-images.githubusercontent.com/41294720/125898973-50a96acb-eacd-4dd0-a78f-8a45a44951bf.png)

**Comment by csjliang** [comment]
你好，感谢关注。
我训练时没有遇到类似情况，请检查一下训练集是否整体偏红。
关于PSNR：这个任务因为是无监督的，所以PSNR没有意义，代码中计算的应该是相对于输入图的PSNR，在训练过程中，由于色彩亮度等越来越接近target分布，所以PSNR自然是越来越低的。

**Comment by wml666** [comment]
> 你好，感谢关注。
> 我训练时没有遇到类似情况，请检查一下训练集是否整体偏红。
> 关于PSNR：这个任务因为是无监督的，所以PSNR没有意义，代码中计算的应该是相对于输入图的PSNR，在训练过程中，由于色彩亮度等越来越接近target分布，所以PSNR自然是越来越低的。

感谢回答，那就期待您release季节转换的模型和数据集啦

**Comment by wml666** [comment]
推测是数据集的原因

**Comment by vitamin520** [comment]
@wml666 您好，请问您最后解决测试结果整体偏红的问题了吗？我现在也出现了这样的问题，但是我的数据集里面基本没有红色场景。非常期待您的回答。

**Comment by Lisicong9203** [comment]
@wml666 @vitamin520 请问两位解决了这个问题了吗，我把模型改成了绿幕抠图，预测结果也是偏红，我是用的 成对数据集，只用MSE loss 没用gan loss
<img width="1397" alt="截屏2021-08-20 下午2 22 28" src="https://user-images.githubusercontent.com/8938339/130189287-8c074380-b7e8-4a34-8af5-d1c555d7c7d8.png">

**Comment by hello-trouble** [comment]
@wml666  @vitamin520  您好，打扰了。我现在也碰到了类似的问题，图片整体结果偏红色，不知道是什么原因，我用有监督的方法训练也不行，你们怎么解决的呢？恳请指教。

**Comment by yanliliu01** [comment]
Hello, 

it seems that when the input sizes for training and inference are different, there will be bandings on the 4 edges of the output. For example, in the results shown by @wml666 . Do you have any comments on this? 

Thanks a lot!
