### ISSUE TITLE
关于论文中金字塔层数与性能的问题请教！

### ISSUE THREAD

**Issue by chenyuanpengcyp** [csjliang/LPTN#2]
在论文中有这样的描述：
     Take the task on 1080p images an an example, the PSNR of the LPTN is just reduced from 22.09 to 21.95 when the L is increased from 3 to 5, yet the model achieves a speed-up of more than x2 and takes about 1/16 of memory usage. 以及对应的table 里面也可以看出L = 5 时比L =3 时要快。这个时间的衡量，指的是整个推理的时间？按照常理理解不应该是L越大，层数越多，推理时间越慢！

**Comment by csjliang** [comment]
你好！金字塔层数越多，低频分量的分辨率越低，低频分量过网络所需要的处理时间越短（每多一层，低频分量的长宽分别减少一半）。因为本文关注低频（亮度、颜色等）相关任务，模型计算量集中在低频处理网络，因此层数越多，对推理时间增益越大。

**Comment by chenyuanpengcyp** [comment]
> 你好！金字塔层数越多，低频分量的分辨率越低，低频分量过网络所需要的处理时间越短（每多一层，低频分量的长宽分别减少一半）。因为本文关注低频（亮度、颜色等）相关任务，模型计算量集中在低频处理网络，因此层数越多，对推理时间增益越大。

感谢回复，已经理解
