### ISSUE TITLE
图像去雾任务

### ISSUE THREAD

**Issue by vitamin520** [csjliang/LPTN#20]
您好，请问一下LPTNet可以用于图像去雾任务吗？

**Comment by csjliang** [comment]
你好，
这个视数据多样性以及退化程度而定。由于LPTN在高频分量上的参数量非常少，因此很难在一个通用场景下生成足够多的细节。因此，如果数据场景较单一且退化（雾）不严重，可以尝试；如果是通用自然场景或退化严重，建议使用传统去雾方法。如果对运行效率要求不高，也可以尝试加深高频分量处的网络。

**Comment by vitamin520** [comment]
好吧，我知道了，谢谢。
