### ISSUE TITLE
迭代次数的设置

### ISSUE THREAD

**Issue by vitamin520** [csjliang/LPTN#21]
您好，请问一下我使用LPTN进行图像增强（具体来说是要去除图像中由于散射而造成的模糊，对比度降低及其他原因造成的颜色失真），我的成对数据集是6128对，那么我的iter应该设置多少比较合适？

**Comment by csjliang** [comment]
你好，
成对数据集使用pixel-wise loss进行训练会比较稳定，训练结果（PSNR）随迭代次数会逐渐增加，建议设置一个较大的iteration数如300K（或更大）。

**Comment by vitamin520** [comment]
谢谢您的回复，我知道了。
