### ISSUE TITLE
will you release the datasets and model for  day2night and sum2win

### ISSUE THREAD

**Issue by azuryl** [csjliang/LPTN#22]
Dear  csjliang 
Thank you for your great job.

I just watched your code and datasets. I'm a little confused to your datasets.in Issue6 ,you said  will release the datasets about  day2night and sum2win. is it include day2night and sum2win.

BR

**Comment by csjliang** [comment]
Hi,
Thanks for your attention. We may not be able to release these data and models due to some copyright issues. Sorry about that. However, we are managing a more comprehensive and large-scale day-to-night dataset. Please stay tuned. Thanks.

**Comment by rotem154154** [comment]
is there any update regard to day2night model?
