### ISSUE TITLE
预训练模型测试的结果

### ISSUE THREAD

**Issue by vitamin520** [csjliang/LPTN#25]
你好，我使用的是您提供的预训练模型，但是结果(中间的图片)跟您论文中提供的并不一样，请问一下我是哪里做的有问题吗？
结果如下图所示。
![alb_LPTN_FiveK_2K](https://user-images.githubusercontent.com/66958249/127491983-4acfd7ee-0ab5-4a0c-91b6-5fc6e3ce4fae.png)

**Comment by csjliang** [comment]
你好，
目前提供的模型是最近改进过的，请参考readme Notes中的解释。

**Comment by vitamin520** [comment]
首先非常感谢您的回复。
您的意思是提供的预训练模型是在论文基础上改进过的模型吗？但是就上图所展示的，主观感受似乎没有论文中的图效果好，请问您知道是怎么回事吗？谢谢。

**Comment by csjliang** [comment]
是改进过的模型。改进后，整体PSNR有一定提升，说明多数图像向GT靠近。但受限于GAN训练的特性以及视觉效果的主观性，无法保证每张图都有提升。谢谢。

**Comment by vitamin520** [comment]
好吧，感谢您的回复。
我在查看您的判别器结构时，发现您似乎有意使用多个判别器，我也想针对不同的level使用多个判别器，将一个复杂的任务分为多个子任务，但是
首先我发现您有两个多判别器结构，请问它们的不同结构是什么原因导致的？
此外，如果对于一个三层的拉普拉斯金字塔，输入图像被分为三个高频分量和一个低频分量，但是您仅使用了三个判别器，是为什么呢？
最后，对于多判别器的损失函数我似乎没有在您提供的代码中发现，请问一下这方面您的训练策略是什么呢？
非常期待您的回复，感谢。

**Comment by csjliang** [comment]
你好，
多判别器可以理解为多尺度，即为了对不同图像尺度的特征进行判别，将图像进行多次下采样，在不同的分辨率上进行判别（参考[Pix2PixHD](https://github.com/NVIDIA/pix2pixHD/blob/master/models/networks.py)），这里的多尺度对应的是一个高斯金字塔，都是在图像空间。我们并没有在拉普拉斯金字塔的高频分量上进行判别。

**Comment by vitamin520** [comment]
您好，非常感谢您的回复。
您说您没有在拉普拉斯金字塔上对高频分量进行判别是针对多判别器做的操作吗？如果是的话，那您是对哪些分量进行了判别？
期待您的回复，谢谢。

**Comment by csjliang** [comment]
你好，对多次下采样的图像进行判别。请参考[Pix2PixHD](https://github.com/NVIDIA/pix2pixHD/blob/master/models/networks.py)中的MultiscaleDiscriminator类，谢谢。

**Comment by vitamin520** [comment]
好的，谢谢。
