### ISSUE TITLE
Fine Tuning the model

### ISSUE THREAD

**Issue by AhmedHashish123** [csjliang/LPTN#26]
If I want to fine tune the model, do I only have to change train_FiveK.yml?
I should open this options file and go to "path" then pretrain_network_g: and set the path of the pretrained model correct?
This should load in the pretrained weights and continue updating these weights right?

**Comment by csjliang** [comment]
Hi,
Sure, you only need to specify the path of the pretrained model in the yml file. Thanks.

**Comment by AhmedHashish123** [comment]
@csjliang  thank you for the fast reply.
