### ISSUE TITLE
No module named 'codes.utils.download_util'; 'codes.utils' is not a package

### ISSUE THREAD

**Issue by lkp520** [csjliang/LPTN#27]
When I run: python scripts/data_preparation/download_datasets.py
I meet:
ModuleNotFoundError: No module named 'codes'

and after I run pip install codes, and run python scripts/data_preparation/download_datasets.py, I meet the problem:
ModuleNotFoundError: No module named 'codes.utils.download_util'; 'codes.utils' is not a package

How can I solve it? Thank you!

**Comment by monkeypaul** [comment]
> When I run: python scripts/data_preparation/download_datasets.py I meet: ModuleNotFoundError: No module named 'codes'
> 
> and after I run pip install codes, and run python scripts/data_preparation/download_datasets.py, I meet the problem: ModuleNotFoundError: No module named 'codes.utils.download_util'; 'codes.utils' is not a package
> 
> How can I solve it? Thank you!

Hi! May I ask how did you solve this problem? Thanks！
