### ISSUE TITLE
Compare with Contrastive Learning for Unpaired Image-to-Image Translation(CUT)?

### ISSUE THREAD

**Issue by zeng-hello-world** [csjliang/LPTN#28]
Hi, this is a great work, but I have a question:
For unpaired data, LPTN also works and I noticed another paper:  [Contrastive Learning for Unpaired Image-to-Image Translation(CUT, ECCV 2020)](http://taesung.me/ContrastiveUnpairedTranslation/). Have you compared them?

thx~

**Comment by csjliang** [comment]
Sorry for the late reply. We do not compare with that paper. We have different goals (we for efficiency and they for effectiveness) on different sub-tasks. Perhaps one can find a proper combination of them. Thanks!
