### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by IDKiro** [csjliang/LPTN#3]
Congratulations on the acceptance of the paper by CVPR, the following are a few questions：
1. The results of Image Retouching under unpaired setting in the paper are not good, so how high PSNR can the method achieve using supervised training?
2. The paper only has the experimental results of summer2winter, but not winter2summer, is this because the results of the latter are far inferior to the former?
3. The images are downloaded from Flickr, is it that the dataset won't be open source?
Thanks!

**Comment by csjliang** [comment]
Hi, thanks for your questions.

1. Unpaired Retouching in FiveK uses 2250 images in the source domain and other 2250 images in the target domain, where only self-reconstruction loss and adversarial loss can be used. Therefore, it can hardly outperform that with paired settings when comparing PSNR. Recently, we have optimized the training and improved the PSNR, where the codes and models will be released soon. In supervised training, one can directly use the MSE loss to pursue high PSNR or use the MSE+GAN loss to balance between PSNR and visual aesthetics. 
2. The winter2summer task (as well as the night2day task) requires generating new textures relating to high-frequency components. As the LPTN is very light-weighted on high-frequency, it may not perform well on such tasks. We are doing extended works to solve this limitation. 
3. The dataset will be open-sourced recently. We need some time to arrange and check the images. Thanks!

**Comment by IDKiro** [comment]
Got.
Thanks for your answer.
