### ISSUE TITLE
 Hi, I have some questions about your code

### ISSUE THREAD

**Issue by wangweiran970922** [csjliang/LPTN#33]
I want to ask something about LP （Laplacian Pyramid）.I use your code to decompose gt（groundtruth） for high frequency and low frequency, and perform LP inverse transformation on them.But there is a big gap between the results  and gt，For example, MSE can reach more than 100.
So I want to know  why?  Have you verified this?

**Comment by csjliang** [comment]
The code has been verified. Please provide more information so we can discuss it. Thanks.

**Comment by wangweiran970922** [comment]
This package is my test sample, the test_gt folder is label, the GT folder is the result I obtained through LP inverse transformation, the clear folder is the high and low frequency obtained through LP transformation, and the GT1 folder is change the method of upsample and the result obtained by multiplying by the multiple of the kernel， text results in each folder.There are two py files that I disassembled with your code, so I hope you can help me to see whether they are correct.May I add your wechat if it's convenient.Thanks!



从QQ邮箱发来的超大附件

1123demo.rar (209.64M, 2021年12月23日 21:10 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=78383334b7d3d696e5e370671e63014b0b0b05560b015202145e5102594e0754085d1e0d0b5a0a495d5e50050e0704050c0d0457386f3355080a00505d0e5c4a4b59413405&code=98348c3d

**Comment by wangweiran0922** [comment]
Hi, do you have any new results to discuss?thanks.
