### ISSUE TITLE
No such file or directory: 'datasets/FiveK/FiveK_train_source.lmdb\\meta_info.txt'

### ISSUE THREAD

**Issue by hangxiaotian** [csjliang/LPTN#34]
学长，您好，当我运行train.py时候，出现了这种情况，文件夹里面存在meta_info.txt，其所在的路径为\LPTN\LPTN-main\scripts\data_preparation\datasets\FiveK\FiveK_train_source.lmdb\meta_info.txt

**Comment by csjliang** [comment]
你好，请检查一下是否如readme所述设置PYTHONPATH。

**Comment by hangxiaotian** [comment]
> 你好，请检查一下是否如readme所述设置PYTHONPATH。

谢谢学长，问题已经解决。

**Comment by StarsRen** [comment]
学长您好，请问PYTHONPATH="./:${PYTHONPATH}"是什么含义，还有上述您二位讨论的PYTHONPATH怎么设置
