### ISSUE TITLE
Can conditional (paired) image-to-image translation be done using LPTN?

### ISSUE THREAD

**Issue by vgthengane** [csjliang/LPTN#35]
Hello @csjliang,

Thank you for sharing your implementation. 

I am working on a shadow generation for cars, I tried working with the pix2pix model but the results were a bit pixelated and I was not able to get high-resolution images. I want to use an image of size `1200x1600` is it possible to work on paired image-to-image translation code with your implementation? If yes, what are the necessary changes I need to make in order it to work?

Thanks in advance.

Best,
@vgthengane

**Comment by csjliang** [comment]
Hello,
When paired training data is ready, the LPTN can be applied to the paired I2I Translation and can improve efficiency. Please use the pixel-wise loss between gt and predicted only. Also, you can adjust the size of the network to balance the efficiency and effectiveness according to your computation resources. Thanks!

**Comment by vgthengane** [comment]
Hi, @csjliang Thank you for your reply. I'll make the necessary changes and update you on my progress. 

Thanks again.

**Comment by vgthengane** [comment]
According to [this](https://github.com/csjliang/LPTN/issues/14#issuecomment-862848948), I need to change the content from [here](https://github.com/csjliang/LPTN/blob/c170460dcb307053b8faab7cdf4660b31d2e8134/options/train/LPTN/train_FiveK.yml#L84) right?

From, 
```
  pixel_opt:
    type: MSELoss
    loss_weight: 1000
    reduction: mean
  gan_opt:
    type: GANLoss
    gan_type: standard
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: 1
  gp_opt:
    loss_weight: 100
```

to, 

```
  pixel_opt:
    type: MSELoss
    loss_weight: 10  # decreased MSE weight
    reduction: mean
  # deleted this part
  gp_opt:
    loss_weight: 10 # decreased MSE weight
```

Is it right?

Update:
 
When I updated files as mentioned above and by commenting the `gan_loss` on lines 130-135 in `lptn_mode.py` I am running into the following error.
```
  File "codes/train.py", line 207, in main
    model.optimize_parameters(current_iter)
  File "/home/vgthengane/Desktop/Upwork/Samuel-Park/shadow-generation-lptn/codes/models/lptn_model.py", line 136, in optimize_parameters
    l_g_total.backward()
  File "/home/vgthengane/venv/pix2pixHD/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/vgthengane/venv/pix2pixHD/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

PS: I am working with transparent image (i.e 4 channel image).

**Comment by vgthengane** [comment]
Hi @csjliang, I have modified the code to run on 4-channel images but I am suffering from bad results. I used the following configurations. 
```
scheduler:[
      type: MultiStepLR
      milestones: [5000, 10000, 20000, 30000]
      gamma: 0.5
    ]
    total_iter: 30000
    warmup_iter: -1
    pixel_opt:[
      type: MSELoss
      loss_weight: 100
      reduction: mean
    ]
    gan_opt:[
      type: GANLoss
      gan_type: standard
      real_label_val: 1.0
      fake_label_val: 0.0
      loss_weight: 1
    ]
    gp_opt:[
      loss_weight: 100
    ]
    net_d_iters: 1
    net_d_init_iters: 0
  ]
```
I really need to do this, Please help me.

![39f454d60b1544dfb96bdbc438a45098_28000](https://user-images.githubusercontent.com/39587792/149664369-d5888ce6-65ee-479d-a22a-15656fee1240.png)

**Comment by csjliang** [comment]
Hi,

Sorry for the late reply. Please remove the GAN loss in both the configuration file and the model file. In specific, you should remove the codes of discriminators and the optimization of D in the LPTN_model.py. Thanks.

**Comment by vgthengane** [comment]
I did not understand the part about removing the discriminator. So I will be using only a generator network like encoder-decoder, no discriminator will be there, right? Can you explain this to me?

Thanks

Updates:
I removed GAN loss from both `.yml` and `LPTN_model.py` files and Discriminator loss from `.yml` and whole discriminator optimization code from the `LPTN_model.py` file. But the model is not converging. What should I do? This is after 90000 iterations and I have 500-500 images in both domain.

![4fc1cd56640042fa86e1dc6a48114eb7_15000](https://user-images.githubusercontent.com/39587792/150622759-dbff4dce-5013-481a-b479-b675e25bc29c.png)

**Comment by csjliang** [comment]
Hi, sorry for the late reply.
As I am not very familiar with the shadow generation task, I guess you may constrain the calculation of losses on the area of shadows, to make the training more stable. Thanks.

**Comment by vgthengane** [comment]
Thank for the reply, I completed the project with some other method.
