### ISSUE TITLE
How to Eliminate Artifacts Due to the Corase to Fine Mode of the LPTN Network

### ISSUE THREAD

**Issue by jxust01** [csjliang/LPTN#37]
Thank you for your research and sharing your code!
But In my scene, some artifacts are generated on the border and around salient objects.
I guess this is caused by corase to fine mode of the LPTN Network ,
and I would like to know how to improve this kind of problem, can you give me some advices? thanks!

**Comment by csjliang** [comment]
Hi, thanks for your attention and sorry for the late reply.
You may also try to use pixel-wise loss only to avoid the artifacts issues. Please refer to my answer in #36. Thanks.
