### ISSUE TITLE
Drawing inference on unpaired images

### ISSUE THREAD

**Issue by Suhaskj1691** [csjliang/LPTN#41]
Hi,

I would like to know if there is a way to draw inference on a single image. For example, I input an summer time image and I get a winter time image as the output? So far, everything I have tried to make this happen, it is expecting a ground truth image as well. I tried to modify the test_FiveK.yaml file by changing the dataset type to UnPairedImageDataset but even then the model expects a groundtruth file. Am I missing somthing here? 
Any help would be appreciated.
Thanks

**Comment by csjliang** [comment]
Hi,

Thanks for your question. You can comment the lines related to reading and processing the gt images in the dataset file. And also, please comment the lines about calculating metrics (e.g., psnr) in the yml file, as calculating these full-reference metrics also expects the gt image. Thanks!

**Comment by Suhaskj1691** [comment]
Thank you
