### ISSUE TITLE
LPTN_arch.py

### ISSUE THREAD

**Issue by ghost** [csjliang/LPTN#42]
![image](https://user-images.githubusercontent.com/38597848/162717122-480e9448-c4d2-43b1-97b6-edb6e4cd10ac.png)

貌似代码中的mask upsample后的网络结构和论文的figure2给出的结构有出入？
或者是我哪里理解错了？

**Comment by ghost** [comment]
我在LPTN_paper_arch.py中找到了对应paper的结构代码。

**Comment by ghost** [comment]
请问为什么会有一个paper版本，一个无paper的版本？关于mask重建的不同，对最后的结果影响有数据记录？

**Comment by csjliang** [comment]
你好，感谢关注。我们在Readme中有注明，更新后的版本相对论文报告的版本整体上有性能提升，供大家参考。有关详细实验结果我们没有具体整理。

**Comment by ghost** [comment]
> 你好，感谢关注。我们在Readme中有注明，更新后的版本相对论文报告的版本整体上有性能提升，供大家参考。有关详细实验结果我们没有具体整理。

感谢解惑！
