### ISSUE TITLE
Pretrained models and datasets

### ISSUE THREAD

**Issue by delldu** [csjliang/LPTN#6]
Dear friends,
     Thank you for your wonderful work. it is real good job.
     By the way, we want to know:
     1) your current pretrained model on google drive could be used to do day2night or sum2win transformer ? If not, would you like share us your day2night/sum2win model ?
     2) When you release day2night/sum2win datasets ?
    Best Regards,

**Comment by csjliang** [comment]
Hi, thanks for your positive comment.
1) the released model is trained on the FiveK dataset that is also released on our google drive. Therefore, it only suits the photo retouching task defined on FiveK. The day2night and sum2win model will also be released when we release the datasets.
2) we will arrange the data after these busy days. We will release the datasets in about a month.

**Comment by delldu** [comment]
Thanks a lot, we are looking forward to your release.
