### ISSUE TITLE
LS-GAN & Multi-scale discriminator

### ISSUE THREAD

**Issue by echoofluoc** [csjliang/LPTN#8]
In 3.4 Learning criteria, the paper mentions the adversarial loss is computed based on the LS-GAN and a multi-scale discriminator	,but when I look into the train_FiveK_paper.yml , it seems you didn't use those criterias? 

As suggested in provided config yml, standard GAN and single discriminator are used to formulate adversarial learning , does the latter setting work better(in PSNR metric or better visual quality)?

**Comment by csjliang** [comment]
Hi. Thanks for your question. In our recent experiment, we found that the WGAN criteria (single discriminator with gradient penalty) lead to better performance both quantitatively and qualitatively, so we recommend this setting for follow-up works.  One possible attempt in the future might be discriminating on each frequency band and construct a 'multi-frequency discriminator'.
