### ISSUE TITLE
No such file or directory: 'datasets/FiveK/FiveK_test_source.lmdb\\meta_info.txt'

### ISSUE THREAD

**Issue by Aryan-Solanki** [csjliang/LPTN#9]
I wanted to use pretrained model . so I didn't download the dataset and imdb 
![Screenshot 2021-05-29 215622](https://user-images.githubusercontent.com/37494973/120077589-be156f00-c0c8-11eb-9104-334547614833.png)

**Comment by csjliang** [comment]
Hi, you need to update the ```dataroot``` in the ```test_FiveK.yml``` file if you want to enhance your own data using pretrained models.

**Comment by Aryan-Solanki** [comment]
how and in which format should i give my input img

**Comment by Aryan-Solanki** [comment]
![image](https://user-images.githubusercontent.com/37494973/120091782-df5b7700-c12b-11eb-8f02-bfaae498559c.png)
what value should i give in datarooot_gt and dataroot_lq

**Comment by Aryan-Solanki** [comment]
can you explain imdb format

**Comment by Aryan-Solanki** [comment]
leave it i found the issue..
change type from imdb to disk
